apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: rideshare
  source:
    repoURL: 'https://github.com/Business-Aware-Control-Plane/gitops.git'
    targetRevision: HEAD
    path: charts/cloudnative-pg
    helm:
      valueFiles:
        - ../../clusters/development/values/platform/cloudnative-pg-operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
