apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository | default "rabbitmq" }}:{{ .Values.image.tag | default "3-management" }}"
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 60
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.credentialsSecretName | default "rabbitmq-credentials" }}
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.credentialsSecretName | default "rabbitmq-credentials" }}
                  key: password
            - name: RABBITMQ_MNESIA_BASE
              value: /var/lib/rabbitmq/mnesia
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size | default "512Mi" }}
