apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: rideshare
  source:
    repoURL: 'https://github.com/Business-Aware-Control-Plane/gitops.git'
    targetRevision: HEAD
    path: charts/jaeger
    helm:
      valueFiles:
        - ../../clusters/development/values/observability/jaeger.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
